<a href="https://colab.research.google.com/github/alscop/ESAA-25-2/blob/main/ESAA_YB_WEEK01_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [6]:
print("NumPy version: ", np.__version__)
np.show_config()

NumPy version:  2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker:

#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
vector1 = np.zeros(10)
print(vector1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [9]:
print("Memory size: ", vector1.nbytes)

Memory size:  80


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [10]:
vector1[4] = 1
print(vector1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [12]:
vector2 = np.arange(start=10, stop=50)
print(vector2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [13]:
print(vector2[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [15]:
array1 = np.arange(9)
array2 = array1.reshape(3,3)
print(array2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [29]:
array3 = np.array([1,2,0,0,4,0])
array0 = np.arange(6)
array4 = array0[array3 != 0]

print(array4)

[0 1 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [41]:
array5 = np.zeros(9)
matrix1 = array5.reshape(3,3)

for i in [0,1,2]:
  matrix1[i,i] = 1

print(matrix1)




[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [46]:
array6 = np.random.random(size=(3,3,3))
print(array6)

[[[0.16220031 0.56450296 0.63233289]
  [0.57590686 0.13588818 0.67384686]
  [0.03343824 0.36670018 0.38318979]]

 [[0.62375164 0.29152614 0.22507945]
  [0.33597232 0.04695364 0.13663012]
  [0.30636913 0.33981334 0.73454325]]

 [[0.12416485 0.94854351 0.66932196]
  [0.80798201 0.5419163  0.13604635]
  [0.08015975 0.5842001  0.33828851]]]
[[[0.16220031 0.56450296 0.63233289]
  [0.57590686 0.13588818 0.67384686]
  [0.03343824 0.36670018 0.38318979]]

 [[0.62375164 0.29152614 0.22507945]
  [0.33597232 0.04695364 0.13663012]
  [0.30636913 0.33981334 0.73454325]]

 [[0.12416485 0.94854351 0.66932196]
  [0.80798201 0.5419163  0.13604635]
  [0.08015975 0.5842001  0.33828851]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [52]:
array7 = np.random.random((10,10))
min_value = np.min(array7)
print("Minimum: ", min_value)

max_value = np.max(array7)
print("Maximum: ", max_value)

Minimum:  0.0009063747365877228
Maximum:  0.9883872216558393


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [55]:
array8 = np.random.random(size=30)
mean_value = np.mean(array8)
print(mean_value)

0.528385860789161


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [79]:
array2d = np.ones((5,5))
array2d[1:-1, 1:-1] = 0
print(array2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, True

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [66]:
array9 = np.zeros((5,5))

for i in [1,2,3,4] :
  array9[i, i-1] = i
print(array9)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [71]:
array10 = np.zeros((8,8))

array10[0::2,1::2] = 1
array10[1::2,0::2] = 1

print(array10)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [73]:
np.unravel_index(100,(6,7,8))

(np.int64(1), np.int64(5), np.int64(4))

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [78]:
X_value = np.random.random((5,5))
X_mean = np.mean(X_value)
X_std = np.std(X_value)

Z = (X_value - X_mean)/X_std
print(Z)

[[-0.02766789  0.99011117 -1.73037859 -1.24381326 -0.18575016]
 [ 0.18811462 -1.36796886 -1.22448351 -0.5735573   0.25300697]
 [ 0.90121292  0.17968449  1.66122644 -0.33526164 -0.47216986]
 [-0.24361451  1.16693586  0.8881785  -0.02492346  0.97007145]
 [-1.78314381 -0.98547027  0.25870283  1.90846611  0.83249176]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [80]:
np.dtype([("R", np.ubyte),("G",np.ubyte),("B",np.ubyte),("A", np.ubyte)])

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])