# Chaepter01 : 파이썬 기반의 머신러닝과 생태계 이해

## 01. 머신러닝의 개념

머신러닝: 애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법

### 머신러닝의 분류

[지도학습]
- **분류**
- **회귀**
- 추천 시스템
- 시각/음성 감지/인지
- 텍스트 분석, NLP

[비지도학습]
- 클러스터링
- 차원 축소
- 강화 학습


### 데이터 전쟁

데이터, 머신러닝 알고리즘 모두 중요한 요소.  
머신러닝은 데이터에 매우 의존적.  
-> 데이터를 이해하고 효율적으로 가공, 처리, 추출해 최적의 데이터를 기반으로 알고리즘을 구동할 수 있도록 준비하는 능력이 중요함.


### 파이썬과 R 기반의 머신러닝 비교

개발 생산성, 지원 패키지, 생태계 측면에서 머신러닝 분야에서 인기 있음

R: 통계 전용 프로그램 언어. 많은 통계 패키지를 보유.  
파이썬: 다양한 영역에서 사용. 개발 전문 프로그램 언어. 프로그래밍 주류 언어.

**"파이썬은 소리없이 프로그래밍 세계를 점령하고 있는 언어"**  
딥러닝 프레임 워크에서 파이썬 우선 정책 시행중 + 파이썬을 중심으로 발전될 것.


## 02. 파이썬 머신러닝 생태계를 구성하는 주요 패키지

- 머신러닝 패키지
  - 사이킷런(Scikit-Learn)
- 행렬/선형대수/통계 패키지
  - 넘파이(NumPy)
  - 사이파이(SciPy)
- 데이터 핸들링
  - 판다스: 2차원 데이터 처리 특화
- 시각화
  - 맷플롯립(Matplotlib): 세분화된 API, 투박한 디자인이 단점.
  - 시본(Seaborn): 맷플롯립 기반, 판다스와 쉬운 연동, 함축적인 API, 다양한 그래프/차트 제공


**넘파이, 판다스 이해가 매우 중요**  
사이킷런의 머신러닝 알고리즘에 입력하기 위한 데이터의 추출/가공/변형, 원하는 차원 배열로의 변환 등 머신러닝 알고리즘 처리 결과에 대한 다양한 가공 등으로 코드를 작성.

## 03. 넘파이

NumPy(Numerical Python)
- 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원
- 루프 사용 X 빠른 배열 연산 속도
- C/C++ 저수준 언어 기반 호환 API 제공
- 다양한 데이터 핸들링 기능 제공 But 판다스가 더 편리

### 넘파이 ndarray 개요

다차원 배열 쉽게 생성, 다양한 연산 수행 가능

In [1]:
import numpy as np #as np 약어로 모듈 표현하는 것이 관례


`array()` ndarray로 변환  
크기, 행&열의 수로 배열 차원도 알 수 有

`np.array()`: ndarray로 반환  
인자로 리스트 객체 [], [[]]가 주로 사용됨. 배열 차원, 크기 표현 쉬움

**`ndarray.shape`**: ndarray의 차원, 크기를 tuple 형태로 나타냄
- (3,): *1차원 array*, 데이터 3개
- (2,3): 2차원 array, 데이터 2*3=6개
- (1,3): 2차원 array, 데이터 3개

`ndarray.ndim`: 각 array의 차원 확인 ...

In [2]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [3]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim,
                                                           array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


### ndarray의 데이터 타입

데이터값: 숫자 값, 문자열 값, 불 값 등 모두 가능
데이터 타입: ndarray 내에서는 **같은 데이터 타입만 가능**  
-> 다른 데이터 유형이 섞여있는 경우, 데이터 크기가 더 큰 데이터 타입으로 형 변환 일괄 적용.
- int & 문자열 -> 문자열
- int & float -> float형

**`ndarray.dtype`**: 데이터 타입 확인 가능

**`ndarray.astype('')`**: 데이터값 타입 변경 가능, 문자열로 지정.
- float -> int : 메모리 절약, 소수점 이하 생략




In [5]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [6]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [7]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

테스트용 데이터 만들기 / 대규모 데이터 일괄 초기화에 사용.

**`arange()`**: array를 range()로 표현  
함수 인자 = stop 값. 0부터 함수 인자 값 -1까지의 값을 순차적으로 변환.

`zeros((,), dtype='')`: 지정 shape를 가진 모든 값이 0인 ndarray 반환
`ones((,))`: ... 모든 값이 1인 ...



In [8]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [9]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)



### ndarray의 차원과 크기를 변경하는 reshape()

`ndarray.reshape(,)`: 특정 차원, 크기로 변환.  
인자로 **'-1'** 적용시 고정된 값에 맞춰 자동으로 생성해 변환됨  
(단, 변경 가능한 사이즈 입력해야함)
- reshape(-1,1): 자주 사용. 2차원, 반드시 1개의 칼럼을 가진 ndarray로 변환. 형태 통일에 유용

* `ndarrayName.tolist()`:리스트 자료형으로 변환.

In [12]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [13]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [14]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [15]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [16]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

인덱싱: ndaraay 내의 일부 데이터 세트나 특정 데이터만을 선택하는 것

1. 특정 데이터만 추출: 원하는 위치의 인덱스 값 지정.
2. 슬라이싱(Slicing): 연속된 인덱스상의 ndarray를 추출.  
  - '시작 인덱스:종료 인덱스' -> 시작 인덱스 ~ 종료 인덱스-1 위치
3. 팬시 인덱싱(Fancy Indexing): 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정, 해당 위치
4. 불린 인덱싱(Boolean Indexing): 특정 조건에 해당 여부 T/F 값 인덱싱 집합에서 True에 해당하는 인덱스 위치

#### 단일 값 추출

1차원 ndarray에서 ...
`arrayName[]`: 인덱스 값 입력, 지정.  
단일 값 추출에서만 데이터 타입이 ndarray가 아니라 그 내의 '데이터값'의 타입이 됨.

In [18]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


*인덱스에 **마이너스 기호** 이용하면 맨 뒤에서부터 지정 가능  
*지정해서 데이터값 수정 가능

In [21]:
print('맨 뒤의 값:', array1[-1], ' 맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9  맨 뒤에서 두 번째 값: 8


In [22]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


2차원 ndarray에서 단일 값 추출  
`arrayName[,]`: 행, 렬 인덱스의 값 추출됨
axis 0(행/row), axis 1(열/col), axis 2(높이) ...


In [23]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


#### 슬라이싱

`arrayName[:]`: <u>종료인덱스 -1</u>까지 반환하는 점 주의.

- [:100] = [0(맨 처음부터):100]
- [10:] = [10:(맨 끝까지)]
- [:] = [(맨 처음부터):(맨 끝까지)]

2차원 이상의 경우  
`arrayName[,]`: 슬라이싱, 단일 값 인덱스 혼용 가능

뒤에 오는 인덱스를 없애면 한 차원 낮아진 ndarray를 반환.
- array2d[0] -> axis 0(row)의 첫 번째 ndarray 반환, 1차원이 됨


In [25]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [27]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [28]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [29]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


#### 팬시 인덱싱

인덱스 집합 지정해 해당 위치의 인덱스에 해당하는 ndarray 반환.


In [30]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2] # 인덱스 (0,2), (1,2)로 적용됨
print('array2d[[0,1],2] => ', array3.tolist())

array4 = array2d[[0,1], 0:2] # 인덱스 ((0,0), (0,1)), ((1,0),(1,1)) 적용됨
print('array2d[[0,1], 0:2] => ', array4.tolist())

array5 = array2d[[0,1]] # 인덱스 ((0:), (1:)) 적용
print('array2d[[0,1]] => ', array5.tolist())



array2d[[0,1],2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


#### 불린 인덱싱

조건 필터링 + 검색 동시에 가능.
사용 多  
for loop/if else 문보다 간단하게 조건문 이용 가능.

`ndarrayName[ 조건문 ]`  
1. 필터링 조건을 [] 안에 기재. T/F 조건으로 반환된 ndarray가 됨
2. False 값은 무시, True 값이 있는 '위치 인덱스 값'이 반환
3. 저장된 인덱스 값으로 데이터 세트 반환.



In [32]:
array1d = np.arange(start=1, stop=10)
# [] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [33]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [34]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [35]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


### 행렬의 정렬 - sort()와 argsort()

#### 행렬 정렬

`np.sort()`: 넘파이에서 sort() 호출. 원 행렬은 그대로 유지, 정렬된 행렬을 새로 반환  
`ndarrayName.sort()`: 행렬 자체에서 sort() 호출. 원 행렬 자체를 정렬한 형태로 변환, 반환 값 None. -> 따로 print 해야함

오름차순 정렬이 기본.
내림차순 정렬 -> **`[::-1]`** 적용.
- np.sort()[::-1]

2차원 이상의 행렬일때, axis 축 값 설정 -> 로우 방향/칼럼 방향으로 정렬 수행 가능
- 로우 방향 정렬: np.sort(ndarrayName, axis=0).
한 칼럼 내에서 로우방향으로 오름차순 정렬
- 칼럼 방향 정렬: np.sort(ndarrayName, axis=1).
한 로우 내에서 칼럼방향으로 오름차순 정렬



In [36]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)
# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [38]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [39]:
array2d = np.array([[8,12],
                    [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


#### 정렬된 행렬의 인덱스를 반환하기

**`np.argsort()`**: 원본 행렬이 정렬되었을 때, 정렬된 행렬의 기존 원본 행렬의 원소 인덱스를 반환.

내림차순 정렬 시 `np.argsort()[::-1]`

넘파이의 데이터 추출에서 많이 사용됨.
실제 값과 그 값이 뜻하는 메타데이터를 별도의 ndarray로 각각 가져야 할 때 사용 多




In [40]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [41]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [42]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

#### 행렬 내적(행렬 곱)

`up.dot(,)`
앞 행렬의 low와 뒤 행렬의 col의 원소들을 순차적으로 곱한 뒤 그 결과를 모두 더한 값. low부터 채우게 됨.
- 내적 결과 n행 m열 = A행렬의 n행 X B행렬의 M열 차례로 곱해 더한 값.
- A행렬의 n행 = B행렬의 M열 개수 동일해야 함


#### 전치 행렬

`transpose()`

원 행렬에서 행과 열 위치를 교환한 행렬.
- A행렬의 n행 M열 -> M행 n열로 교환.
- A^T로 표기

In [43]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array( [[7,8],
               [9,10],
               [11,12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과: \n', dot_product)

행렬 내적 결과: 
 [[ 58  64]
 [139 154]]


In [44]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
